In [52]:
import pandas as pd
import numpy as np

In [53]:
d=[[0,0,0], [0,1,1],[1,0,1], [1,1,0]]
c=['A','B','A XOR B']

In [54]:
data = pd.DataFrame(d,columns=c)

In [55]:
data

A  B  A XOR B
0  0  0        0
1  0  1        1
2  1  0        1
3  1  1        0

In [56]:
X_train=data[['A','B']]

In [57]:
Y_train=data['A XOR B']

In [58]:
X_train= np.array(X_train)
Y_train=np.array(Y_train)

In [62]:
X_train=X_train.T
X_train

array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [63]:
X_train.shape,W.T.shape

((2, 4), (1, 2))

In [88]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [72]:
numOfTrainSamples=X_train.shape[1]
numOfTrainSamples

4

In [79]:
np.dot(W.T, X_train)+b

array([[-1.01453457,  0.09686897, -1.91265961, -0.80125607]])

In [81]:
from sklearn.metrics import log_loss

In [82]:
Y_train

array([0, 1, 1, 0])

In [83]:
Y_train=np.expand_dims(Y_train,axis=0)

In [149]:
W=np.random.randn(2,1)

In [150]:
W

array([[ 0.01895371],
       [-0.81488242]])

In [151]:
b=np.random.randn()
b

1.3482823715966896

In [152]:
a=0.01
for i in range(100):
    #--- Accumulation
    Z=np.dot(W.T,X_train)+b
#     print(Z)
    #--- Activation Fun
    A=sigmoid(Z)
    
#     #--- Normalize to 1,0
    A=np.where(A<0.5,0,1)
    print(A)
    #--- Errror
    error=log_loss(Y_train,A)
    print('error: ',error)
#     # gradient decsent
    dz=A-Z
    dw=np.dot(X_train,dz.T)/numOfTrainSamples
    db=np.sum(dz,axis=1)/numOfTrainSamples
    
    W=W-a*dw
    b=b-a*db
    

[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]
error:  2.772588722239781
[[1 1 1 1]]


In [160]:
#------ Converged weight vectors found using gradient descent-----#
converged_weight_vectors=np.array([[-0.0655864 ],[-1.13591921]])

In [167]:
converged_biased_weight_vector=np.array([1.16386414])

In [168]:
#----- Just testing to see output----#
Z=np.dot(converged_weight_vectors.T,X_train)+converged_biased_weight_vector
    #--- Activation Fun
A=sigmoid(Z)
    
#--- Normalize to 1,0
A=np.where(A<0.5,0,1)
print(A)

[[1 1 1 0]]
